@rem Copyright 2017 gRPC authors.
@rem
@rem Licensed under the Apache License, Version 2.0 (the "License");
@rem you may not use this file except in compliance with the License.
@rem You may obtain a copy of the License at
@rem
@rem     http://www.apache.org/licenses/LICENSE-2.0
@rem
@rem Unless required by applicable law or agreed to in writing, software
@rem distributed under the License is distributed on an "AS IS" BASIS,
@rem WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
@rem See the License for the specific language governing permissions and
@rem limitations under the License.

@rem enter repo root
cd /d %~dp0\..\..\..

@rem Move artifacts generated by the previous step in the build chain.
powershell -Command "mv %KOKORO_GFILE_DIR%\github\grpc\artifacts input_artifacts"
dir input_artifacts

@rem Adjust the location of nuget.exe
@rem set NUGET=nuget.exe
@rem set SIGNTOOL="c:\Program Files (x86)\Windows kits\10\bin\x86\signtool.exe"

powershell -File signnuget.ps1 -nugetfile Grpc.Core.1.18.0.nupkg

@rem %NUGET% update -self
@rem %%NUGET% sign Grpc.Core.1.18.0.nupkg -CertificateSubjectName "Google LLC" -Verbosity detailed -Overwrite -Timestamper  http://timestamp.digicert.com
@rem %SIGNTOOL% 

mkdir artifacts
xcopy /Y /I *.nupkg artifacts\ 
xcopy /Y /I *.nupkg.signed artifacts\ 

bash tools/internal_ci/helper_scripts/delete_nonartifacts.sh
